config/routes.rb
Rails.application.routes.draw do
  root to: 'toppage#index'
  get "home/about" => "about#index"
  get "/users" => "users#index"
  get 'users/follow_list/:user_id' => 'users#follow_list', as: 'follow_list'
  get 'users/follower_list/:user_id' => 'users#follower_list', as: 'follower_list'
  get 'search/search' => 'search#search', as: 'search'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books, only: [:update, :edit, :show, :index, :create, :destroy] do
  	resource :favorites, only: [:create, :destroy]
  	resource :post_comments, only: [:create, :destroy]
  end
  resources :users, only: [:update, :edit, :show, :index, :ensure_correct_user]
  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  attachment :profile_image
  validates :introduction, length: {maximum: 50}
  validates :name, presence: true, length: {minimum: 2, maximum:20}

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

  def follower_count(user)
  	Relationship.where(follow_id: user.id)
  end
  #上記has_manyの:reverse_of_relationshipsと同じ役割

  def self.search(method,search)
      if method == "forward_match"
        @users = User.where("name LIKE ?","#{search}%")
      elsif method == "backward_match"
        @users = User.where("name LIKE ?","%#{search}")
      elsif method == "perfect_match"
        @users = User.where("name LIKE ?","#{search}")
      elsif method == "partial_match"
        @users = User.where("name LIKE ?","%#{search}%")
      else
        @users = User.all
    end
  end

  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
  	@user = User.find(params[:id])
  	@book = Book.new
  	@books = @user.books
  end

  def edit
  	@user = User.find(params[:id])
    if current_user != @user
      redirect_to user_path(current_user)
    end
  end

  def update
  	@user = User.find(params[:id])
  	 if @user.update(user_params)
  	 	flash[:notice] = "You have updated user successfully."
  	    redirect_to user_path(@user.id)
     else
      render action: :edit
     end
  end
  def index
  	@users = User.all
  	@user = current_user
    @book = Book.new
  end

  def create
  params.require(:user).permit(:postcode, :prefecture_name, :address_city, :address_street, :address_building)
  end

  def follow_list
    @user = User.find(params[:user_id])
  end

  def follower_list
    @user = User.find(params[:user_id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction, :email)
  end
end

#確認用http
#http://localhost:3000/

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_button.html.erb
          <% unless current_user == user %>
            <div id="follow_form<%= user.id %>">
              <% if current_user.following?(user) %>
                <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }, remote: true) do |f| %>
                  <%= hidden_field_tag :follow_id, user.id %>
                  <%= f.submit 'フォローを外す', class: 'btn btn-danger btn-block' %>
                <% end %>
              <% else %>
                <%= form_for(current_user.relationships.build, remote: true) do |f| %>
                  <%= hidden_field_tag :follow_id, user.id %>
                  <%= f.submit 'フォローする', class: 'btn btn-primary btn-block' %>
                <% end %>
              <% end %>
              </div>
          <% end %>

app/views/users/_follow_count.html.erb
		<div id="follow_count<%= user.id %>">
            <%= link_to follow_list_path(user, remote: true) do %>
            <label>フォロー数: </label> <%= user.relationships.count %>
            <% end %>
        </div>

app/views/users/_follower_count.html.erb
		<div id="follower_count<%= user.id %>">
            <%= link_to follower_list_path(user, remote: true) do %>
            <label>フォロワー数: </label> <%= user.follower_count(user).count %>
            <% end %>
        </div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <% if @user.errors.any? %>
    <div id="error-explanation">
      <h2><%= @user.errors.count %> errors prohibited this book from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div class="col-xs-3">

      <h2>User info</h2>


      <%= form_for(@user) do |f| %>

      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :Image %><br>
        <%= f.attachment_field :profile_image %>
      </div>
      <div class="field">
        <%= f.label :Introduction %>
        <%= f.text_area :introduction %>
      </div>
      <div class="actions">
        <%= f.submit "Update User" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/follow_list.html.erb
<div class="container">
  <div class="row">
    <h2>Users</h2>
    <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th></th>
          <th></th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @user.followings.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, :fill, 100, 100, class: "pull-left profile-thumb", fallback: "no_image.jpg" %></td>
          <td><%= user.name %></td>
          <td>
            <p><%= link_to follow_list_path(user) do %>
              フォロー数: <%= user.relationships.count %>
              <% end %>
            </p></td>
            <td><p><%= link_to follower_list_path(user) do %>
              フォロワー数: <%= user.follower_count(user).count %>
              <% end %>
            </p></td>
            <td>
              <% unless current_user == user %>
                <% if current_user.following?(user) %>
                  <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
                    <%= hidden_field_tag :follow_id, user.id %>
                    <%= f.submit 'フォローを外す', class: 'btn btn-danger btn-block' %>
                  <% end %>
                <% else %>
                  <%= form_for(current_user.relationships.build) do |f| %>
                    <%= hidden_field_tag :follow_id, user.id %>
                    <%= f.submit 'フォローする', class: 'btn btn-primary btn-block' %>
                  <% end %>
                <% end %>
              <% end %>
            </td>
            <td><a><%= link_to '詳細', user_path(@user) %></a></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

app/views/users/follower_list.html.erb
<div class="container">
  <div class="row">
    <h2>Users</h2>
    <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th></th>
          <th></th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @user.followers.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, :fill, 100, 100, class: "pull-left profile-thumb", fallback: "no_image.jpg" %></td>
          <td><%= user.name %></td>
          <td>
            <p><%= link_to follow_list_path(user) do %>
              フォロー数: <%= user.relationships.count %>
              <% end %>
            </p></td>
            <td><p><%= link_to follower_list_path(user) do %>
              フォロワー数: <%= user.follower_count(user).count %>
              <% end %>
            </p></td>
            <td>
              <% unless current_user == user %>
                <% if current_user.following?(user) %>
                  <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
                    <%= hidden_field_tag :follow_id, user.id %>
                    <%= f.submit 'フォローを外す', class: 'btn btn-danger btn-block' %>
                  <% end %>
                <% else %>
                  <%= form_for(current_user.relationships.build) do |f| %>
                    <%= hidden_field_tag :follow_id, user.id %>
                    <%= f.submit 'フォローする', class: 'btn btn-primary btn-block' %>
                  <% end %>
                <% end %>
              <% end %>
            </td>
            <td><a><%= link_to '詳細', user_path(user) %></a></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
<% if @book.errors.any? %>
  <div id="error-explanation">
    <h2><%= @book.errors.count %> errors prohibited this book from being saved:</h2>
        <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
  </div>
<% end %>


    <%= render 'books/link', book: Book.new, user: @user %>
     <div class="col-xs-9">
<h2>Users</h2>
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <% unless current_user == user %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, :fill, 100, 100, class: "pull-left profile-thumb", fallback: "no_image.jpg" %></td>
        <td><%= user.name %></td>
        <td>
          <%= render 'users/follow_count', user: user %>
        </td>
        <td>
          <%= render 'users/follower_count', user: user %>
        </td>
        <td>
          <%= render 'users/follow_button', user: user %>
        </td>
        <td><a><%= link_to 'Show', user %></a></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
<% if flash[:notice] %>
<div>
    <p class="flashtop"><%= flash[:notice] %></p>
</div>
<% end %>



<%= render 'books/link', book: @book, user: @user %>
    <div class="col-xs-9">
<h2>Books</h2>
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinon</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user.id) do %>
          <%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, class: "pull-left profile-thumb", fallback: "no_image.jpg" %>
          <% end %>
        </td>
        <td>
           <%= link_to book_path(book.id) do %>
           <%= book.title %>
           <% end %>
        </td>
        <td><%= book.body %></td>
        <td>
          <div>
            <a>コメント数: <%= book.post_comments.count %></a>
          </div>
      </td>
      </tr>
    <% end %>
  </tbody>
</table>
    </div>
  </div>