config/routes.rb
Rails.application.routes.draw do
  root to: 'toppage#index'
  get "home/about" => "about#index"
  get "/users" => "users#index"
  get 'users/follow_list/:user_id' => 'users#follow_list', as: 'follow_list'
  get 'users/follower_list/:user_id' => 'users#follower_list', as: 'follower_list'
  get 'search/search' => 'search#search', as: 'search'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books, only: [:update, :edit, :show, :index, :create, :destroy] do
  	resource :favorites, only: [:create, :destroy]
  	resource :post_comments, only: [:create, :destroy]
  end
  resources :users, only: [:update, :edit, :show, :index, :ensure_correct_user]
  resources :relationships, only: [:create, :destroy]
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
        def favorited_by?(user)
          favorites.where(user_id: user.id).exists?
        end
  has_many :post_comments, dependent: :destroy
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
	def self.search(method,search)
      if method == 'forward_match'
      @books = Book.where('title LIKE ?',"#{search}%")
      elsif method == 'backward_match'
      @books = Book.where('title LIKE ?',"%#{search}")
      elsif method == 'perfect_match'
      @books = Book.where('title LIKE ?',"#{search}")
      elsif method =='partial_match'
      @books = Book.where('title LIKE ?',"%#{search}%")
      else
      @books = Book.all
      end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
	def index
  	@books = Book.all
  	@book = Book.new
    @user = current_user
  end

  def show
  	@book = Book.find(params[:id])
    @user = @book.user
    @post_comment = PostComment.new
  end

  def edit
  	@book = Book.find(params[:id])
    @user = @book.user
    if current_user != @user
      redirect_to books_path
    end
  end

  def create
  	@book = Book.new(book_params)
  	@book.user_id = current_user.id
  	if @book.save
  		flash[:notice] = "You have created book successfully."
  	    redirect_to book_path(@book)
  	else
  		@books = Book.all
      @user = current_user
  		render action: :index
  	end
  end

  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		flash[:notice] = "You have updated book successfully."
  	    redirect_to book_path(@book)
    else
      render action: :edit
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path
  end

  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_comment.html.erb
<%= form_with model: [book, post_comment], remote: true do |f| %>
<div class="row">
  <div class="col-sm-12">
    <%= f.text_area :comment, class: "form-control" %>
  </div>
</div>
<div>
  <%= f.submit "送信する", class: "btn btn-default pull-right" %>
<% end %>
</div>

app/views/books/_comment_list.html.erb
      <tr id="comment_<%= post_comment.id %>">
        <td class="comment-avatar">
          <div class="avatar">
            <%= attachment_image_tag post_comment.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
          </div>
          <% if post_comment.user_id == current_user.id %>
            <div><%= link_to "コメント削除", book_post_comments_path(post_comment.book_id, id: post_comment.id), method: :delete, remote: true, class:"btn btn-danger", data: { confirm: '本当に消しますか？' } %></div>
          <% end %>
        </td>
        <td class="comment-text">
          <div class="comment-author clearfix">
            <a class="link-author"><%= post_comment.user.name %></a>
          </div>
        <td class="comment-entry"><%= post_comment.comment %></td>
        </td>
      </tr>

app/views/books/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
  <div>
      <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
      <i class="glyphicon glyphicon-heart" style="color: red;"></i>
      <%= book.favorites.count %>
    <% end %>
  </div>
<% else %>
  <div>
    <%= link_to book_favorites_path(book), method: :post, remote: true do %>
    <i class="glyphicon glyphicon-heart-empty"></i>
    <%= book.favorites.count %>
    <% end %>
  </div>
<% end %>

app/views/books/_link.html.erb
<div class="col-xs-3">


  <h2>User info</h2>
  <div class="profile-container">

   <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, class: "pull-left profile-thumb", fallback: "no_image.jpg" %>
   <table class="table">
    <tbody>
      <tr>
      	<th><p>name</p></th>
        <th><p><%= user.name %></p></th>
      </tr>
      <tr>
        <th><p>introduction</p></th>
        <th><p><%= user.introduction %></p></th>
      </tr>
      <tr>
        <th><p>follows</p></th>
        <th>
          <%= render 'users/follow_count', user: @user %>
        </th>
      </tr>
      <tr>
          <th><p>followers</p></th>
          <th>
          <%= render 'users/follower_count', user: @user %>
          </th>
          </p></th>
      </tr>
      </table>
      <div class="row">
        <% if user.id == current_user.id %>
          <%= link_to edit_user_path(user) do %>
            <span class="glyphicon glyphicon-wrench col-xs-12 btn btn-default"></span>
          <% end %>
        <% else %>
          <%= render 'users/follow_button', user: @user %>
        <% end %>
      </div>
    </div>

    <h2>New book</h2>

    <%= form_for(book) do |f| %>
    <% if book.errors.any? %>
    <div id="error-explanation">
      <h2><%= book.errors.count %> errors prohibited this book from being saved:</h2>
      <ul>
        <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div class="field row">
      <div class="field">
        <%= f.label :Title %><br>
        <%= f.text_field :title, class: "book_Title col-xs-12" %>
      </div>
      <div class="field">
        <%= f.label :Opinion %><br>
        <%= f.text_area :body, class: "book_Opinion col-xs-12" %>
      </div>
      <div class="actions">
        <%= f.submit "Create Book", :class=>"col-xs-12 btn btn-primary"%>
      </div>
    </div>
    <% end %>
  </div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
<% if @book.errors.any? %>
  <div id="error-explanation">
    <h2><%= @book.errors.count %> errors prohibited this book from being saved:</h2>
        <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
  </div>
<% end %>
      <div class="col-xs-3">
<h2>Editing Book</h2>

<%= form_for(@book) do |f| %>
  <div class="field">
    <%= f.label :Title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :Opinion %>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit "Update Book" %>
  </div>
<% end %>
<% if @book.user.id == current_user.id %>
<%= link_to "Show", book_path(@book) %>
<span>|</span>
<%= link_to "Back", books_path %>
<% end %>
</div>
</div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
<% if @book.errors.any? %>
  <div id="error-explanation">
    <h2><%= @book.errors.count %> errors prohibited this book from being saved:</h2>
        <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
  </div>
<% end %>
<%= render 'books/link', book: Book.new, user: @user %>
    <div class="col-xs-9">
<h2>Books</h2>
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinon</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user.id) do %>
          <%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, class: "pull-left profile-thumb", fallback: "no_image.jpg" %>
          <% end %>
        </td>
        <td>
           <%= link_to book_path(book.id) do %>
           <%= book.title %>
           <% end %>
        </td>
        <td><%= book.body %></td>
        <td id="favorite-<%= book.id %>">
          <%= render partial: "favorite", locals: { book: book } %>
       </td>
       <td>
         <div>
           <a>コメント数: <%= book.post_comments.count %></a>
         </div>
       </td>
      </tr>
    <% end %>
  </tbody>
</table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">

    <% if flash[:notice] %>
    <div>
      <p class="flash"><%= flash[:notice] %></p>
    </div>
    <% end %>
あたおか
    <%= render 'books/link', book: Book.new, user: @user %>
    <div class="col-xs-9">
      <h2>Book detail</h2>
      <div class="blog-box-content">
        <table class="table">
          <thead>
            <tr></tr>
          </thead>
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(@book.user.id) do %>
                <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, class: "pull-left profile-thumb", fallback: "no_image.jpg" %>
                <br>
                <%= @user.name %>

                <% end %>
              </td>
              <td>
               <p class="title">
                 <%= link_to book_path(@book) do %>
                 <%= @book.title %>
                 <% end %>
               </p>
             </td>
             <td>
              <p class="opinion">
                <%= @book.body %>
              </p>
              <td id="favorite-<%= @book.id %>">
                <%= render partial: "favorite", locals: {book: @book } %>
              </td>
              </td>
              <td>
              <div>
                <a>コメント数: <%= @book.post_comments.count %></a>
              </div>
              </td>
              <% if @book.user.id == current_user.id %>
              <td><%= link_to "Edit", edit_book_path(@book), class:"btn btn-success" %></td>
              <td><%= link_to 'Destroy', book_path(@book), method: :delete, class:"btn btn-danger", data: { confirm: '本当に消しますか？' } %></td>
              <% end %>
            </tr>
          </tbody>
        </table>
        <div>
          <table class="table">
          <thead>
            <tr>
              <td></td>
              <td>Name</td>
              <td>Comment</td>
              <td></td>
              </tr>
          </thead>

          <tbody id="comment-<%= @book.id %>">
          <% @book.post_comments.each do |post_comment| %>
          <%= render partial: 'comment_list', locals: { post_comment: post_comment } %>
          <% end %>
          </tbody>
        </table>

        </div>
        <div>
        <% if user_signed_in? %>
      <!-- コメント入力欄をブログの詳細ページに表示するためのrender -->
          <%= render partial: 'comment', locals: { book: @book, post_comment: @post_comment } %>
    <% end %>
      </div>
    </div>
  </div>
</div>